### ISSUE TITLE
Visualizing child regions when looking at locations bigger than cities

### ISSUE THREAD

**Issue by pbeshai** [m-lab/mlab-vis-client#15]
![image](https://cloud.githubusercontent.com/assets/793847/17818633/6f2dc114-6612-11e6-9be6-12020e6fed06.png)

**Comment by pbeshai** [comment]
Unlikely we get this in before completion

**Comment by georgiamoon** [comment]
Could we have a way to explore the location list more than in the search box? That might address this issue.
