### ISSUE TITLE
Firefox - dotted lines not kept on hover

### ISSUE THREAD

**Issue by vlandham** [m-lab/mlab-vis-client#219]
Only seen in firefox. On hover, dotted line effect is lost. 

In Firefox:

<img width="846" alt="screen shot 2016-10-21 at 2 51 01 pm" src="https://cloud.githubusercontent.com/assets/9369/19612910/339dc1cc-979e-11e6-85cf-f5e7fcf263e5.png">

In Safari:
<img width="713" alt="screen shot 2016-10-21 at 2 54 18 pm" src="https://cloud.githubusercontent.com/assets/9369/19612928/4489e006-979e-11e6-8f56-da3965022fe5.png">

**Comment by pbeshai** [comment]
This is a strange bug. I think it is a problem with Firefox. It appears to not re-interpret the clip-path property of the path. A workaround would be to add a setTimeout-0 function that re-sets the clip path to whatever it is currently. This may be a side effect of setting `clip-path` in the `<path>` before the clip path is created and Firefox not trying to resolve it again after it has been created.

![ffbug](https://cloud.githubusercontent.com/assets/793847/19657007/4e54b10c-99f0-11e6-85e1-340e88ddbda7.gif)
