### ISSUE TITLE
Hover over region name should highlight line, highlight bars

### ISSUE THREAD

**Issue by vlandham** [m-lab/mlab-vis-client#240]
Should function just as the ISP hover over does.

<img width="312" alt="screen shot 2016-11-01 at 8 56 15 am" src="https://cloud.githubusercontent.com/assets/9369/19896304/119b1d88-a011-11e6-9050-94a6cdab94b9.png">

**Comment by pbeshai** [comment]
This issue happens due checking that the highlighted ID exists in the `series` array-- but it should also check `annotationSeries`, where location resides.
