### ISSUE TITLE
Feature Requests - do more with maps

### ISSUE THREAD

**Issue by critzo** [m-lab/mlab-vis-client#256]
More contextual information on the front page map might be helpful for usability. For example a click or hover event that provides more detail about what this map is, why it's there, etc. As is, it's intent is to communicate where M-Lab tests generally originate, and M-Lab's global scale, but users report expecting it to to be interactive.

**Comment by georgiamoon** [comment]
@critzo yeah -- I was thinking of even just making this a catch all "do more with maps" feature request issue 👍
