### ISSUE TITLE
Add BQ shortcut below the viz

### ISSUE THREAD

**Issue by georgiamoon** [m-lab/mlab-vis-client#261]
Just an idea, but if possible, we could expose the BQ queries in the viz view so that people who are familiar with the data can start from our queries. Might be too complex because of the aggregated table structure but an idea nonetheless

**Comment by iros** [comment]
We could generate the queries based on some of the other parameters we have selected like:
* Date Range
* Location
* Aggregation level (day/month etc)

I don't believe we have the ISP data in the original BQ tables, so we couldn't easily point to that... is that changing?
