### ISSUE TITLE
Make available hourly or more granular raw data

### ISSUE THREAD

**Issue by collina** [m-lab/mlab-vis-client#265]
Request sent to support:

> Generally, residential users suffer the most when the ISP underperforms during the night and business users suffer the most when the ISP underperforms during the day. However - I wish there was a way to filter speed tests conducted by hour of the day. Hour-by-hour reports help everyone clearly convey a pattern of underperformance.

**Comment by georgiamoon** [comment]
@collina thanks for adding this -- I was just coming to check, and saw you already had :)
