### ISSUE TITLE
Explore options for providing users more than medians in the visualizations

### ISSUE THREAD

**Issue by georgiamoon** [m-lab/mlab-vis-client#274]
User email to support: 

> I viewed the comparison of Comcast to Verizon for my town.   Comcast appears to be much much  slower.  Until I realized this is just AVERAGE data.  So perhaps it's just the case that there are many more "low end" customers with Comcast, paying for slower service, so it skews the visualization
http://viz.measurementlab.net/location/nauspasouderton
>
> You should give the end user running the test the option to enter what their internet speed is SUPPOSED to be (i.e. what are they paying for.)  In my case I pay for 75/75 from Verizon FIOS, and get around 80/80.    To me, thats GREAT.
> What I'd like to know when making the comparison, is what kind of speeds Comcast customers get, RELATIVE TO WHAT THEY PAY FOR.

M-Lab doesn't collect data about what people are supposed to get, we just get raw measurements when people run tests. It would potentially be helpful to users to be able to see more than medians on the site, since medians can be impacted by the user base (both positively and negatively). We could also explore a way to allow users to input data about their connection as a way to look at tests with similar speeds -- e.g. how many tests are similar to their results or different. Similar to the idea we've discussed around having a way for a user to run a test while on the viz site and compare their results to the data from the area they are in.

**Comment by iros** [comment]
I think we considered adding binned data into our tables in the past. I'll have to try and sort out why we didn't. Might have just been timing. I think that's doable though, and we can add a band around each line on hover, for example, to show the 5%-95% spread?

**Comment by georgiamoon** [comment]
@iros yeah, we should play with ideas and think about use cases we want to serve. We might also just want to think about how people get to the histogram views of the data or what other questions they have
