### ISSUE TITLE
Decide whether to continue using a BigTable Cluster JSON files in GCS

### ISSUE THREAD

**Issue by critzo** [m-lab/mlab-vis-client#292]
It has been suggested by @pboothe that `mlab-vis-api` and the BigTable cluster that drives it, could be replaced by saving a bunch of JSON files to a public GCS bucket, and rewriting `mlab-vis-client` to use those instead of the api/BigTable.

Once #291 is completed, it should be easy enough to output both to a BigTable cluster and to JSON files in GCS, to test whether the front-end client can perform responsively with just JSON. We'll also need to evaluate whether the JSON output needs to change.

**Comment by laiyi-ohlsen** [comment]
Decided GCS Json @critzo to add more detail

**Comment by critzo** [comment]
@pboothe and I discussed a strategy for using JSON extracts of statistics in GCS, using an expected URL path structure to emulate an api. That structure will be:
`gs://api.measurementlab.net/<continent_code>/<country_code>/<ISO3166-2_region_code_subdiv1>/`
