### ISSUE TITLE
Test count bars should line up with the middle of the line chart points

### ISSUE THREAD

**Issue by iros** [m-lab/mlab-vis-client#80]
Right now they are anchored to the beginning of the bars

**Comment by pbeshai** [comment]
We discussed this and it seems the solutions are:

1. put space between the y-axis and the start of the x-axis. This keeps the y-axis of the main chart and the count chart aligned. Or
2. offset the bars to line up with the points. This makes the y-axis of the count chart not line up with the y-axis of the main chart. 

I think both are less visually appealing than having the test count bars not centered with the points in line charts. If I had to choose, I'd go with option 1.
