### ISSUE TITLE
Check how things are looking on diff browsers

### ISSUE THREAD

**Issue by iros** [m-lab/mlab-vis-client#84]
Georgia mentioned there might be an issue, but she isn't 100% sure what it is. We should check if things are rendering ok on Firefox

**Comment by pbeshai** [comment]
## IE11
### Home Page
- [ ] not showing tangram map

### Location Page
- [ ] lines get real scribbly on hover / initial render in line chart and small mults
- [ ] small mults don't update on change metric
- [ ] changing time fails to load data for hour chart, time series and small mults

### Compare Page
- lines get less scribbly here... weird.

**Comment by pbeshai** [comment]
There was a bug in d3-interpolate-path with IE that has now been fixed in v1.0.2 which fixes the scribbly lines.
